ui: tape
server: ./testserver.js
capabilities:
  record-video: false
  video-upload-on-pass: false
  record-screenshots: false
browsers:
  - name: ie
    version: 10..latest
  - name: firefox
    version: latest
  - name: chrome
    version: latest
  - name: ipad
    version: 8.0..latest
  - name: iphone
    version: 8.0..latest
