ui: tape
server: ./testserver.js
capabilities:
  record-video: false
  video-upload-on-pass: false
  record-screenshots: false
browsers:
  - name: firefox
    version: latest
  - name: chrome
    version: latest
  - name: safari
    version: latest
